# Generated by Django 3.1.5 on 2022-02-12 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('json', models.JSONField()),
                ('main_text_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.texts')),
            ],
        ),
    ]
