# Generated by Django 3.1.5 on 2021-02-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_ycomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ycomment',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
