# Generated by Django 3.1.5 on 2022-02-17 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaharaImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_pesak', models.CharField(choices=[('good', 'טהור'), ('bad', 'טמא'), ('rabbi_q', 'שאלת רב'), ('cant_see', 'לא רואים ברור')], max_length=250)),
                ('release_date', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logo', models.TextField(blank=True)),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='logo')),
                ('showed_to', models.CharField(blank=True, choices=[('', '')], max_length=250, null=True)),
                ('second_pesak', models.CharField(blank=True, choices=[('good', 'טהור'), ('bad', 'טמא'), ('rabbi_q', 'שאלת רב'), ('cant_see', 'לא רואים ברור')], max_length=250, null=True)),
                ('rabbi_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
