# Generated by Django 3.1.5 on 2022-03-02 07:22

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taharaimage',
            name='logo_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='taharaimage',
            name='second_pesak',
            field=models.CharField(blank=True, choices=[('good', 'טהור'), ('bad', 'טמא'), ('rabbi_q', 'שאלת רב'), ('cant_see', 'לא רואים ברור')], max_length=250, null=True, verbose_name='פסק'),
        ),
        migrations.AlterField(
            model_name='taharaimage',
            name='showed_to',
            field=models.CharField(blank=True, choices=[('', ''), ('', '')], max_length=250, null=True),
        ),
    ]
