# Generated by Django 3.1.5 on 2022-05-08 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taharaimage',
            name='color_percentage',
            field=models.JSONField(blank=True, default={}),
        ),
        migrations.AlterField(
            model_name='taharaimage',
            name='showed_to',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
