# Generated by Django 3.1.5 on 2022-03-02 09:04

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0002_auto_20220302_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taharaimage',
            name='logo_image',
        ),
        migrations.AddField(
            model_name='taharaimage',
            name='image',
            field=cloudinary.models.CloudinaryField(default=None, max_length=255, verbose_name='image'),
        ),
    ]
