# Generated by Django 3.1.5 on 2022-05-18 18:41

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0003_waittime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taharaimage',
            name='image2',
            field=cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='image2'),
        ),
    ]
