# Generated by Django 3.1.5 on 2022-12-24 22:17

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0004_auto_20220518_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taharaimage',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='taharaimage',
            name='image2',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='image2'),
        ),
    ]
